-- PostgreSQL Node 0: Create databases db_0, db_1, db_2, db_3

CREATE DATABASE db_0;
CREATE DATABASE db_1;
CREATE DATABASE db_2;
CREATE DATABASE db_3;

-- Grant permissions
GRANT ALL PRIVILEGES ON DATABASE db_0 TO lab6;
GRANT ALL PRIVILEGES ON DATABASE db_1 TO lab6;
GRANT ALL PRIVILEGES ON DATABASE db_2 TO lab6;
GRANT ALL PRIVILEGES ON DATABASE db_3 TO lab6;
