-- PostgreSQL Node 1: Create databases db_4, db_5, db_6, db_7

CREATE DATABASE db_4;
CREATE DATABASE db_5;
CREATE DATABASE db_6;
CREATE DATABASE db_7;

-- Grant permissions
GRANT ALL PRIVILEGES ON DATABASE db_4 TO lab6;
GRANT ALL PRIVILEGES ON DATABASE db_5 TO lab6;
GRANT ALL PRIVILEGES ON DATABASE db_6 TO lab6;
GRANT ALL PRIVILEGES ON DATABASE db_7 TO lab6;
