-- PostgreSQL Node 2: Create databases db_8, db_9, db_a, db_b

CREATE DATABASE db_8;
CREATE DATABASE db_9;
CREATE DATABASE db_a;
CREATE DATABASE db_b;

-- Grant permissions
GRANT ALL PRIVILEGES ON DATABASE db_8 TO lab6;
GRANT ALL PRIVILEGES ON DATABASE db_9 TO lab6;
GRANT ALL PRIVILEGES ON DATABASE db_a TO lab6;
GRANT ALL PRIVILEGES ON DATABASE db_b TO lab6;
